language: java
addons:
  sonarcloud:
    organization: "cfc-kata"
    token:
      secure: "hN4qo0/sZR8nMWcxEHkZ/qe3ahWbREOcqpAKjv/ctc2KIJr8kmYvofX4zDJXR9TByvCVo9/u9dR17zEa2sd5YFsLYHjm4qolkXqG9r0ijRhnfonon8aQWGhDmuxblWNDuQJg8mxLpurNHrpGnQ69wng//NtCQHiCkW500bQ1eN9hoqxMKAFLpOT4aNsMz+4/yk5gkGTW2DJR8QOdCTbDdmMJx9htXYwwVpOaxkW4xY6yDoIcpdJ40INb6Cs1xDmb1jhrjzZKsV+Ciey20bvNcm64Upjhf5qZaqe3eN5aUwuuxoDyjtmkB3Y34Tl7b3ppypBL8khqbLAqSTmLdRZ5uHbvKgA3kamB7abdKKBaGboG/AUCur2hbVsvzKW1t548TsOY6SFgvhzQKzBw+aKXzE0KimpfdqsZsu/SC7gcsGz5ZcqjpvwmKreDv8G6t2l809uh0QgW8UMtNp9Zn9vfTUhJ7ld2lG8kUTkXtWKFapmOvBw1Rfq8vp0HhGnk+Ia0HiuEwoJOQDOf5GlSW2V2ykTTsxXxohlMjlnC4YuysW3cXw7EEWxVd3QMWxfGVtILdVh32tbpXOJTyn58Z/lszARNknQYZbF+iMLl6fnQp+L9lTcDlvExEuE5QCFWSrS8zEiavMwIxs3+q5RTkQk/GzH7icqaG+daTdU539h/veQ="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cfc-kata_cfc-kata-loan-team-c
